# Generated by Django 3.2.7 on 2024-02-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_setting', '0004_alter_company_logo_alter_company_video_streaming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='camer_type',
            field=models.CharField(choices=[('digest Auth Camera', 'digest Auth Camera'), ('Basic Auth Camera', 'Basic Auth Camera')], default='digest Auth Camera', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='camera_ip',
            field=models.CharField(default='192.168.1.188', max_length=255),
        ),
    ]
