# Generated by Django 3.2.7 on 2024-02-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_setting', '0006_rename_camer_type_company_camera_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='123456', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
